### PR TITLE
Run builds in parallel

### PR DESCRIPTION
**Pull request by buthed010203**
I didn't test this as I cant be bothered to setup the android project but this should work fine

### CODE REVIEW

**Comment by Toxopid82** [comment]
- [ ] t

**Comment by Toxopid82** [comment]
k :d

**Comment by USMP-lancer** [comment]
might not work now with changes to the build.yml

**Comment by buthed010203** [comment]
can you stop commenting on this ffs

**Comment by USMP-lancer** [comment]
lmao

**Comment by buthed010203** [comment]
stop oh my god

**Pull request closed without merging**
